### ISSUE TITLE
Help needed to make things work on Raspberry Pi

### ISSUE THREAD

**Issue by Krakapuk** [Dean151/Aln-NodeJs#12]
Hello,
Thank you very much for your work. 
This S25 feeder seemed nice at the beginning, but when I discover how it really works it was a nasty surprise !

So after crawling the web trying to take back control on it, I find your providential api !
I followed your readme.md file, and I managed :
-  to create a raspberry wifi hotspot and to connect the feeder to hit
- to install your api and may be to run it using either pm2 or node 

I say "may be to run it" because when I try to communicate with the feeder using curl:
`curl -d '{"identifier": "MYFEEDERID"}' -H "Content-Type: application/json" -H "Accept: application/json" -X POST http://localhost/api/feeder/claim`
I have this in return:
> <html>
> <head><title>404 Not Found</title></head>
> <body bgcolor="white">
> <center><h1>404 Not Found</h1></center>
> <hr><center>nginx/1.10.3</center>
> </body>
> </html>

I am not sure the curl command is OK because I never used it before and it is not detailled in your readme file. Especially, you do not specify a specific port to use on localhost, so I try 80. 
Indeed in the config file of nginx the port 80 seems to be the one of the nginx server, but again, It was the first time I used a reverse proxy, so I may be (surely) wrong... 
I noticed that in the config.js file and in nginx config file, a port 3000 is mentionned, but it is not clear for me if it is the one that should be use to communicate with the feeder ? On my raspberry, it appears to be close or something like that, because when I use it with the curl command:
`curl -d '{"identifier": "MYFEEDERID"}' -H "Content-Type: application/json" -H "Accept: application/json" -X POST http://localhost:3000/api/feeder/claim`
it returns "connection denied".

However, l also have an error related to port in log file (/home/pi/.pm2/logs/alnpet-error.log) for pm2, but also if I use `node /home/pi/Aln-NodeJs/main.js`):

> express-session deprecated req.secret; provide secret option src/server.js:59:13
> [2019-03-30T14:57:34.863Z] Listening to port 9999
> /home/pi/Aln-NodeJs/src/database-coordinator.js:36
>         throw err;
>         ^
> 
> Error: connect ECONNREFUSED 127.0.0.1:3306
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
>     --------------------
>     at Protocol._enqueue (/home/pi/Aln-NodeJs/node_modules/mysql/lib/protocol/Protocol.js:144:48)
>     at Protocol.handshake (/home/pi/Aln-NodeJs/node_modules/mysql/lib/protocol/Protocol.js:51:23)
>     at Connection.connect (/home/pi/Aln-NodeJs/node_modules/mysql/lib/Connection.js:118:18)
>     at new DataBaseCoordinator (/home/pi/Aln-NodeJs/src/database-coordinator.js:34:14)
>     at Object.<anonymous> (/home/pi/Aln-NodeJs/main.js:32:16)
>     at Module._compile (internal/modules/cjs/loader.js:701:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
>     at Module.load (internal/modules/cjs/loader.js:600:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:531:3)

The error seems linked to a connection on port 3306. 
From your api config.js, this port seems related to mySQL database. I am not sure if a mySQL database should be created and set and may be mandatory to make the api working ? As you do not mentioned it in the readme.md, I supposed this was optionnal, but may be not... ?

I hope my message is not too confusing and that you will have time to help me a little to make things work... Do not hesitate if you need more "debugging information". 
If I can get your API working, I could offer you a modified version of your readme.md file to specifically help beginners like me to use your API ...

Again many thank for your api !

**Comment by Dean151** [comment]
Hello @Krakapuk.

First, you wanna make your feeder to correctly communicate with localhost instead of api.alnpet.com

To do so, enter the IP of your feeder machine in a navigator, use admin/admin combination for the user/password, and look for an URL or an API in the menu (English is available as an option, not only Chinese)

Remplace the API url by your Raspberry Pi IP. It will be enough, no more need for creating your own WIFI to replace the DNS resolution anymore. This was an early version of my API.

Then you'll need to have a working MySQL DB to store infos.
Set ip up, create a DB, a user and provide all the info in the config.js file.
Don't forget to generate a secret for the session.

After that, use the register endpoint to create an account, and then login, and then claim endpoint to register your FeederID to your newly created account.
After that, with your Session cookie, you'll have control of your feeder machine.

**Comment by Dean151** [comment]
If you don't want to bother, You can provide `alnpet.thomasdurand.fr` as an URL for the machine
Then use this one as an API. You'll be my beta tester.
Be sure that if you choose to do so, They may have time when I break something, this is not a production, but rather my own implementation of it for my machine.
Good luck!
