### ISSUE TITLE
Implement feeder association process

### ISSUE THREAD

**Issue by Dean151** [Dean151/Aln-NodeJs#14]

**Comment by natterstefan** [comment]
What exactly does this mean?

**Comment by Dean151** [comment]
My plan was to make my server owning this code public ; and have all the necessary to authenticate a feeder with an account.
Then, only this account would be allowed to communicate with a specific feeder.
But lack of time & motivation made this project on the ice. My current private implementation is enough for my needs.
Maybe someday?

**Comment by natterstefan** [comment]
Ah, that be great. Thanks for investing so much work into this to help others use the devices further even if the original API is offline (which it is as of today...).

**Comment by Dean151** [comment]
Reverse engineering the websocket of the machine was very cool to do. Couldn't have done it without the original API.
I simulated a "fake machine" to connect with their servers, and sent the responses to my machine with my own socket.
With multiple tries, I could start to understand the bytes meaning and make the full picture of it
